<!DOCTYPE html>

<html lang="en">
	<head>
		<title>IS490 - Wrongway Airlines</title>
		
		<link rel='stylesheet' type='text/css' href='./public/styles/main.css' />
		<script type='text/javascript' src='./public/js/main.js'></script>
		
	</head>
	
	<body>
		<div id='div-main-menu'>
			
			<ul id='ul-main-menu'>
				<li><a href='#'>Link</a></li>
				
			</ul>
			<div class='div-clear-both'></div>
		</div>
		
		<?php echo($html); ?>
			
	</body>
</html>
